@user=root
@password=Hashicorp123!
@cookie=cm-login-token=C2nfLtXRlODdutKtaHg7eJ7D8DKSb30W

### login
POST https://172.21.15.254:8081/json

{"service":"login", "username":"root", "password":"Hashicorp123!"}

### example return
HTTP/1.1 200 OK
Connection: close
Content-Length: 4
Content-Type: application/json
Set-cookie: cm-login-token=SyaFbfeiKbS4uWycyTOfZ4OgSCyJFVEk;path=/;Secure;httponly

####
POST https://172.21.15.254:8081/json
Cookie: {{cookie}}

{"service":"CMPart","call":"getSoftwareImages"} 

### example return

HTTP/1.1 200 OK
Connection: close
Content-Encoding: gzip
Content-Length: 2141
Content-Type: application/json
X-U: 11124

[
  {
    "SOLFlowControl": true,
    "SOLPort": "ttyS1",
    "SOLSpeed": "115200",
    "baseType": "SoftwareImage",
    "bootfspart": "f3652da2-2efe-414b-a650-10c8feea5d8f",
    "childType": "",
    "creationTime": 1763006515,
    "enableSOL": false,
    "extra_values": null,
    "fileOperationInProgress": false,
    "fspart": "6e16508d-fa87-4588-81f9-3a30d60a0611",
    "kernelOutputConsole": "tty0",
    "kernelParameters": "rd.driver.blacklist=nouveau",
    "kernelVersion": "6.8.0-51-generic",
    "modified": false,
    "modules": [
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "aacraid",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "c42e374c-683c-4268-b23e-7e04f6bc770d"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "ahci",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "0044a457-1290-4995-a098-c047d0b7db98"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "aic79xx",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "c3981b39-4442-4e3d-b0b5-9fc4544ce492"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "aic7xxx",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "87b2806d-15dd-40a3-b66a-a0251732dc74"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "arcmsr",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "e38c9cb3-3f08-4413-9223-3830cba6ca55"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "hpsa",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "161b32de-f873-4b3f-9ff0-3d06d11d2670"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "megaraid",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "b9f1d434-37a7-428b-9ed2-711e83e93f92"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "megaraid_sas",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "8fda20e0-3ca0-4c45-ae6a-a3801e5464c1"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "mpt3sas",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "c979b21e-9dd5-4d14-a88c-5d937d940c8c"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "mptsas",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "88296103-53a9-48e5-9a37-c897776a4a7c"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "mptscsih",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "ef598bfd-015a-4fa6-94a9-c30a11d6eec4"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "mptspi",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "2edfc34a-760d-456f-bf8a-fccf7d4e10d4"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "sata_nv",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "02209563-68e7-4d47-a4fa-31f693449f61"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "sata_sil",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "308e1ada-6e3c-4cf7-951a-2310cde2955a"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "sata_svw",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "489e7121-88ca-4985-bbd6-d12547dd7cd2"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "bnx2",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "0c88a57f-8eae-49f3-9ec5-aff0dadf11a1"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "bnx2x",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "c072b2e0-5b9a-47e0-9a95-9ccd17850576"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "bridge",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "95f800a6-5aa9-4e7e-9669-ba84c64d5fca"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "br_netfilter",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "5bcd1093-10ae-4dbf-8b4f-7d608f329093"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "e1000",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "5423639b-b311-4f20-ba02-87cb6974cec7"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "e1000e",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "b104a704-644e-407e-a82b-af1185da95d7"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "forcedeth",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "5208d922-b054-4e22-bcb7-d8c75cb10d83"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "igb",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "c360ed97-f0a6-4809-b9ee-bfb2bd820486"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "igbvf",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "7b56656d-2e6c-4ff5-b4bd-19a532c2a0dd"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "ixgbe",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "2797046d-8dd8-435b-8d3e-a72b7885767f"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "ixgbevf",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "91011dc3-3b03-4654-b958-9cad655191e4"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "i40e",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "39127765-cd2c-48ff-8ae6-b57795f4ad64"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "tg3",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "b754e223-bf14-4c8e-a5e4-e6775457b650"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "hv_netvsc",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "4c28ba6f-b369-4fc6-8f31-77d3d5fb693f"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "hv_storvsc",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "f6c25a78-1046-4a61-9b1c-959d3910591a"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "hv_utils",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "7941c5db-fd85-4f61-b1b7-b1239376cae7"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "hv_vmbus",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "b8485b26-a348-4ff4-a2be-3f97f791a9f8"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "btrfs",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "6280d8bc-cf2c-4414-b7bb-cfcfe2542c8b"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "jfs",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "eaf47c2e-5d4d-45a9-9d74-6be9ecc7ade8"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "nfs",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "478f5ed0-e048-4943-9e71-1de700b1ccf5"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "nfsv3",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "e59a8277-3d0e-41f7-97c0-f0262742f2e8"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "nfsv4",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "51160b1e-1e89-4487-8c93-ec778bd272ee"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "reiserfs",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "1b2103e2-272c-45f2-9f38-fbd2c73759fe"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "xfs",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "2f48bbb5-2219-4737-b7cf-317a91799b0d"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "udf",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "d8220f06-ba63-47a5-b417-50f2e22c380a"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "usbhid",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "850b320c-c6c8-40b3-9017-615ebe7cffca"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "dm-persistent-data",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "5196bd9e-6994-4828-9274-46237eee1a39"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "dm-bio-prison",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "01700ab3-bd05-4ca1-8e89-b4ec8b520334"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "dm-bufio",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "1ce4cd7c-eb6a-443a-aef5-1434934877e0"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "dm-thin-pool",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "0a34a9ed-ea36-42ff-9ff8-9d26550f6fbd"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "nvme",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "fbcc50d2-e14f-4c9c-b230-cfd6604b2030"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "isofs",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "90d0d720-1aab-4427-aae6-6584ce456cb6"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "bnxt_en",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "bc2f836a-241d-4e21-95fa-53a60b762af9"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "bonding",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "ad0c686b-58ee-427c-b027-0f4c25aacf2c"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "hpilo",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "d22ad9c8-26f7-408e-919d-585c0568393a"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "ipmi_si",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "3b6c5525-1b4a-4cc4-a4ee-b9ea252f8fad"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "ipmi_ssif",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "6f1c6f01-6394-46ec-94ee-55af34c0850f"
      },
      {
        "baseType": "KernelModule",
        "childType": "",
        "extra_values": null,
        "modified": false,
        "name": "ipmi_devintf",
        "parameters": "",
        "revision": "",
        "to_be_removed": false,
        "uuid": "ef659c48-fb34-4cca-9d76-e6eb41e63057"
      }
    ],
    "name": "default-image",
    "notes": "",
    "originalImage": "00000000-0000-0000-0000-000000000000",
    "parentSoftwareImage": "00000000-0000-0000-0000-000000000000",
    "parent_uuid": "8482c4e9-383c-43de-873f-8c54ee77ee74",
    "path": "/cm/images/default-image",
    "revision": "",
    "revisionHistory": [],
    "revisionID": 0,
    "to_be_removed": false,
    "uuid": "8482c4e9-383c-43de-873f-8c54ee77ee74"
  }
]

### get master node

POST https://172.21.15.254:8081/json
Cookie: {{cookie}}

{"service":"cmdevice","call":"getNode", "arg":"master"}

### example return
HTTP/1.1 200 OK
Connection: close
Content-Encoding: gzip
Content-Length: 2209
Content-Type: application/json
X-U: 9053

{
  "accessSettings": null,
  "authenticationService": "CATEGORY",
  "baseType": "Device",
  "biosSetup": null,
  "bmcSettings": null,
  "chassisPosition": null,
  "childType": "HeadNode",
  "cmdaemonUrl": "https://172.21.15.254:8081",
  "creationTime": 1763006515,
  "customPingScript": "",
  "customPingScriptArgument": "",
  "customPowerScript": "",
  "customPowerScriptArgument": "",
  "customRemoteConsoleScript": "",
  "customRemoteConsoleScriptArgument": "",
  "defaultGateway": "0.0.0.0",
  "defaultGatewayMetric": 0,
  "excludeListManipulateScript": "",
  "extra_values": null,
  "forceFullEnvironment": false,
  "fsexports": [
    {
      "allSquash": false,
      "allowWrite": false,
      "anonGid": 65534,
      "anonUid": 65534,
      "async": true,
      "automatic": true,
      "baseType": "FSExport",
      "checkTree": false,
      "childType": "",
      "disabled": false,
      "extraOptions": "",
      "extra_values": null,
      "fsid": 0,
      "hosts": "",
      "modified": false,
      "name": "/cm/node-installer@managementnet",
      "network": "21b20743-d055-42c6-b03c-583c0c061e2e",
      "path": "/cm/node-installer",
      "rdma": false,
      "revision": "",
      "rootSquash": false,
      "to_be_removed": false,
      "uuid": "8867943b-9822-4f59-a879-eae73c1d4abf"
    },
    {
      "allSquash": false,
      "allowWrite": true,
      "anonGid": 65534,
      "anonUid": 65534,
      "async": true,
      "automatic": true,
      "baseType": "FSExport",
      "checkTree": false,
      "childType": "",
      "disabled": false,
      "extraOptions": "",
      "extra_values": null,
      "fsid": 0,
      "hosts": "",
      "modified": false,
      "name": "/cm/node-installer/certificates@managementnet",
      "network": "21b20743-d055-42c6-b03c-583c0c061e2e",
      "path": "/cm/node-installer/certificates",
      "rdma": false,
      "revision": "",
      "rootSquash": false,
      "to_be_removed": false,
      "uuid": "cafdc5d4-574d-4aae-a963-7e1a13939f65"
    },
    {
      "allSquash": false,
      "allowWrite": false,
      "anonGid": 65534,
      "anonUid": 65534,
      "async": true,
      "automatic": true,
      "baseType": "FSExport",
      "checkTree": false,
      "childType": "",
      "disabled": false,
      "extraOptions": "",
      "extra_values": null,
      "fsid": 0,
      "hosts": "",
      "modified": false,
      "name": "/cm/node-installer@internalnet",
      "network": "84d8d82b-3ae7-4433-a793-bb44d5c3b4fe",
      "path": "/cm/node-installer",
      "rdma": false,
      "revision": "",
      "rootSquash": false,
      "to_be_removed": false,
      "uuid": "5cfb4f16-65df-4aad-81c9-02a920504083"
    },
    {
      "allSquash": false,
      "allowWrite": true,
      "anonGid": 65534,
      "anonUid": 65534,
      "async": true,
      "automatic": true,
      "baseType": "FSExport",
      "checkTree": false,
      "childType": "",
      "disabled": false,
      "extraOptions": "",
      "extra_values": null,
      "fsid": 0,
      "hosts": "",
      "modified": false,
      "name": "/cm/node-installer/certificates@internalnet",
      "network": "84d8d82b-3ae7-4433-a793-bb44d5c3b4fe",
      "path": "/cm/node-installer/certificates",
      "rdma": false,
      "revision": "",
      "rootSquash": false,
      "to_be_removed": false,
      "uuid": "b3c87b0c-24a4-4325-924c-322ff5591101"
    },
    {
      "allSquash": false,
      "allowWrite": true,
      "anonGid": 65534,
      "anonUid": 65534,
      "async": true,
      "automatic": true,
      "baseType": "FSExport",
      "checkTree": false,
      "childType": "",
      "disabled": false,
      "extraOptions": "",
      "extra_values": null,
      "fsid": 0,
      "hosts": "",
      "modified": false,
      "name": "/var/spool/burn@managementnet",
      "network": "21b20743-d055-42c6-b03c-583c0c061e2e",
      "path": "/var/spool/burn",
      "rdma": false,
      "revision": "",
      "rootSquash": false,
      "to_be_removed": false,
      "uuid": "c4c1edb7-04f9-4ad0-a110-31f35044b5a0"
    },
    {
      "allSquash": false,
      "allowWrite": true,
      "anonGid": 65534,
      "anonUid": 65534,
      "async": true,
      "automatic": true,
      "baseType": "FSExport",
      "checkTree": false,
      "childType": "",
      "disabled": false,
      "extraOptions": "",
      "extra_values": null,
      "fsid": 0,
      "hosts": "",
      "modified": false,
      "name": "/var/spool/burn@internalnet",
      "network": "84d8d82b-3ae7-4433-a793-bb44d5c3b4fe",
      "path": "/var/spool/burn",
      "rdma": false,
      "revision": "",
      "rootSquash": false,
      "to_be_removed": false,
      "uuid": "28259ee6-bb32-414a-8d5c-8b40cfa52468"
    },
    {
      "allSquash": false,
      "allowWrite": true,
      "anonGid": 65534,
      "anonUid": 65534,
      "async": true,
      "automatic": true,
      "baseType": "FSExport",
      "checkTree": false,
      "childType": "",
      "disabled": false,
      "extraOptions": "",
      "extra_values": null,
      "fsid": 3455393898,
      "hosts": "",
      "modified": false,
      "name": "/home@managementnet",
      "network": "21b20743-d055-42c6-b03c-583c0c061e2e",
      "path": "/home",
      "rdma": false,
      "revision": "",
      "rootSquash": false,
      "to_be_removed": false,
      "uuid": "a8bca29a-22a8-468d-8154-8b20b467ceaf"
    },
    {
      "allSquash": false,
      "allowWrite": true,
      "anonGid": 65534,
      "anonUid": 65534,
      "async": true,
      "automatic": true,
      "baseType": "FSExport",
      "checkTree": false,
      "childType": "",
      "disabled": false,
      "extraOptions": "",
      "extra_values": null,
      "fsid": 3295442241,
      "hosts": "",
      "modified": false,
      "name": "/cm/shared@managementnet",
      "network": "21b20743-d055-42c6-b03c-583c0c061e2e",
      "path": "/cm/shared",
      "rdma": false,
      "revision": "",
      "rootSquash": false,
      "to_be_removed": false,
      "uuid": "8ed00a2a-4ed8-4cb8-b1cf-3ebad469ec6d"
    },
    {
      "allSquash": false,
      "allowWrite": true,
      "anonGid": 65534,
      "anonUid": 65534,
      "async": true,
      "automatic": true,
      "baseType": "FSExport",
      "checkTree": false,
      "childType": "",
      "disabled": false,
      "extraOptions": "",
      "extra_values": null,
      "fsid": 3627484160,
      "hosts": "",
      "modified": false,
      "name": "/home@internalnet",
      "network": "84d8d82b-3ae7-4433-a793-bb44d5c3b4fe",
      "path": "/home",
      "rdma": false,
      "revision": "",
      "rootSquash": false,
      "to_be_removed": false,
      "uuid": "9225db4a-0cc4-461a-8244-1015e6e4aa34"
    },
    {
      "allSquash": false,
      "allowWrite": true,
      "anonGid": 65534,
      "anonUid": 65534,
      "async": true,
      "automatic": true,
      "baseType": "FSExport",
      "checkTree": false,
      "childType": "",
      "disabled": false,
      "extraOptions": "",
      "extra_values": null,
      "fsid": 1980960275,
      "hosts": "",
      "modified": false,
      "name": "/cm/shared@internalnet",
      "network": "84d8d82b-3ae7-4433-a793-bb44d5c3b4fe",
      "path": "/cm/shared",
      "rdma": false,
      "revision": "",
      "rootSquash": false,
      "to_be_removed": false,
      "uuid": "25e22cbf-4e12-4f4d-a0f9-186a4c09c1f9"
    }
  ],
  "fsmounts": [],
  "gpuSettings": [],
  "hostname": "bcm11-headnode",
  "interfaces": [
    {
      "additionalHostnames": [],
      "alternativeHostname": "",
      "baseType": "NetworkInterface",
      "bootable": false,
      "bringupduringinstall": "NO",
      "cardtype": "Ethernet",
      "childType": "NetworkPhysicalInterface",
      "connectedMode": true,
      "dhcp": false,
      "excludeFromDhcpd": false,
      "extra_values": null,
      "ip": "172.21.15.254",
      "ipv6Dhcp": false,
      "ipv6Ip": "::0",
      "mac": "00:50:56:9B:E4:6D",
      "modified": false,
      "name": "ens33",
      "network": "21b20743-d055-42c6-b03c-583c0c061e2e",
      "onNetworkPriority": 60,
      "revision": "",
      "speed": "",
      "startIf": "ALWAYS",
      "switchPorts": [],
      "to_be_removed": false,
      "uuid": "a88b69fd-c828-4425-99ac-a7cffcbf8e96"
    }
  ],
  "ioScheduler": "",
  "mac": "00:50:56:9B:E4:6D",
  "managementNetwork": "00000000-0000-0000-0000-000000000000",
  "modified": false,
  "notes": "",
  "parent_uuid": "9f885869-a146-4cd6-af1f-f9b6c674a84c",
  "partNumber": "",
  "partition": "ddd19eb5-f04a-48dc-9cc6-f160b704a7dd",
  "powerControl": "none",
  "powerDistributionUnits": [],
  "prometheusMetricForwarders": [],
  "provisioningInterface": "00000000-0000-0000-0000-000000000000",
  "provisioningTransport": "RSYNCDAEMON",
  "proxySettings": null,
  "pxelabel": "",
  "rackPosition": null,
  "revision": "",
  "roles": [
    {
      "addServices": true,
      "baseType": "Role",
      "childType": "HeadNodeRole",
      "disableAutomaticExports": false,
      "extra_values": null,
      "failoverId": 1763010461,
      "modified": false,
      "name": "headnode",
      "revision": "",
      "to_be_removed": false,
      "uuid": "a458760f-3898-4870-bd7d-8127a5ea44b8"
    },
    {
      "addServices": true,
      "baseType": "Role",
      "childType": "StorageRole",
      "disableNFS1": false,
      "disableNFS2": false,
      "disableNFS3": false,
      "disableNFS4": false,
      "extra_values": null,
      "lockdTcpPort": 0,
      "lockdUdpPort": 0,
      "modified": false,
      "mountdPort": 0,
      "name": "storage",
      "nfs4grace": 0,
      "nfsThreads": 0,
      "rdmaPort": 0,
      "revision": "",
      "rquotadPort": 0,
      "statdOutgoingPort": 0,
      "statdPort": 0,
      "to_be_removed": false,
      "uuid": "aea97aa8-cc4e-463a-9eb1-60428dab113c"
    },
    {
      "addServices": true,
      "backupRing": 0,
      "baseType": "Role",
      "childType": "BackupRole",
      "directory": "/var/spool/cmd/backup",
      "disabled": false,
      "extra_values": null,
      "maximumNumberOfBackups": 0,
      "modified": false,
      "name": "backup",
      "revision": "",
      "to_be_removed": false,
      "uuid": "fa585751-553d-4ef0-b4c5-f9aa4d333fe5"
    },
    {
      "addServices": true,
      "backupOnPowerOff": false,
      "backupOnPowerReset": false,
      "backupOnReboot": false,
      "backupOnShutdown": false,
      "backupOnTerminate": false,
      "backupRing": 0,
      "baseType": "Role",
      "childType": "MonitoringRole",
      "delayAfterDown": 600,
      "delayAfterUp": 60,
      "extra_values": null,
      "maximumNumberOfNodes": 16384,
      "modified": false,
      "name": "monitoring",
      "nodeFilters": [],
      "numberOfBackups": 2,
      "revision": "",
      "to_be_removed": false,
      "uuid": "8f0031d7-4dd8-455a-83cf-645710864c6c"
    },
    {
      "addServices": true,
      "allImages": "LOCALDISK",
      "baseType": "Role",
      "categories": [],
      "childType": "ProvisioningRole",
      "extra_values": null,
      "includeRevisionsOfLocalImages": true,
      "loadWeight": 0.0,
      "localImages": [],
      "localProvisioning": true,
      "maxProvisioningNodes": 10,
      "modified": false,
      "name": "provisioning",
      "nodegroups": [],
      "racks": [],
      "revision": "",
      "sharedImages": [],
      "to_be_removed": false,
      "uuid": "deb459de-8aac-4328-8b24-5c3446585608"
    },
    {
      "addServices": true,
      "allowRamdiskCreation": false,
      "baseType": "Role",
      "categories": [],
      "childType": "BootRole",
      "disableAutomaticExports": false,
      "extra_values": null,
      "fsparts": [],
      "imagesFromProvisioningRole": false,
      "modified": false,
      "name": "boot",
      "nodegroups": [],
      "racks": [],
      "revision": "",
      "softwareImages": [],
      "syncFSParts": "AUTO",
      "to_be_removed": false,
      "uuid": "4edca494-8e60-4b4c-9fe4-20496f782db0"
    }
  ],
  "seLinuxSettings": null,
  "serialNumber": "",
  "services": [],
  "staticRoutes": [],
  "supportsGNSS": false,
  "switchPorts": [],
  "timeZoneSettings": null,
  "to_be_removed": false,
  "useExclusivelyFor": "",
  "userDefinedResources": [],
  "userdefined1": "",
  "userdefined2": "",
  "uuid": "9f885869-a146-4cd6-af1f-f9b6c674a84c",
  "versionConfigFiles": false
}
