// Code generated by HashiCorp. DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/compare"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
)

func TestAccCMPartSoftwareImageResource_Basic(t *testing.T) {
	imageName := generateUniqueTestName("test-image")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	// ID consistency tracking across all CRUD operations
	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					// Modern state verification with type-safe matchers
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("path"),
						knownvalue.StringExact(imagePath),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
						knownvalue.NotNull(),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("creation_time"),
						knownvalue.NotNull(),
					),
					// Track ID for consistency across operations
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check after Create
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
			},
			// ImportState testing
			{
				ResourceName:      "bcm_cmpart_softwareimage.test",
				ImportState:       true,
				ImportStateVerify: true,
				// Ignore computed fields that change
				ImportStateVerifyIgnore: []string{"original_image"},
			},
			// Update and Read testing
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Updated(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("notes"),
						knownvalue.StringExact("Updated notes"),
					),
					// Verify ID unchanged after update
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check after Update
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Updated(imageName, imagePath),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}

func TestAccCMPartSoftwareImageResource_FullConfig(t *testing.T) {
	imageName := generateUniqueTestName("test-full")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Full(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("path"),
						knownvalue.StringExact(imagePath),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_parameters"),
						knownvalue.StringExact("quiet splash"),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("notes"),
						knownvalue.StringExact("Test image with full configuration"),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("enable_sol"),
						knownvalue.Bool(true),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("sol_speed"),
						knownvalue.StringExact("115200"),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("modules"),
						knownvalue.ListSizeExact(2),
					),
				},
			},
			// Idempotency check
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Full(imageName, imagePath),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_UpdateKernelConfig(t *testing.T) {
	imageName := generateUniqueTestName("test-kernel-update")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_KernelParams(imageName, imagePath, "quiet"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_parameters"),
						knownvalue.StringExact("quiet"),
					),
				},
			},
			{
				Config: testAccCMPartSoftwareImageResourceConfig_KernelParams(imageName, imagePath, "quiet splash"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_parameters"),
						knownvalue.StringExact("quiet splash"),
					),
				},
			},
			// Idempotency check after update
			{
				Config: testAccCMPartSoftwareImageResourceConfig_KernelParams(imageName, imagePath, "quiet splash"),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_UpdateModules(t *testing.T) {
	imageName := generateUniqueTestName("test-modules-update")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Modules(imageName, imagePath, 1),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("modules"),
						knownvalue.ListSizeExact(1),
					),
				},
			},
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Modules(imageName, imagePath, 2),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("modules"),
						knownvalue.ListSizeExact(2),
					),
				},
			},
			// Idempotency check after update
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Modules(imageName, imagePath, 2),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_UpdateSOL(t *testing.T) {
	imageName := generateUniqueTestName("test-sol-update")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_SOL(imageName, imagePath, false, "9600"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("enable_sol"),
						knownvalue.Bool(false),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("sol_speed"),
						knownvalue.StringExact("9600"),
					),
				},
			},
			{
				Config: testAccCMPartSoftwareImageResourceConfig_SOL(imageName, imagePath, true, "115200"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("enable_sol"),
						knownvalue.Bool(true),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("sol_speed"),
						knownvalue.StringExact("115200"),
					),
				},
			},
			// Idempotency check after update
			{
				Config: testAccCMPartSoftwareImageResourceConfig_SOL(imageName, imagePath, true, "115200"),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_MissingRequired(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: `
provider "bcm" {
  endpoint             = "https://172.21.15.254:8081"
  username             = "root"
  password             = "Hashicorp123!"
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  # Missing required name and path
}
`,
				ExpectError: regexp.MustCompile(`The argument "name" is required`),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_InvalidSOLSpeed(t *testing.T) {
	imageName := generateUniqueTestName("test-invalid-sol")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name      = %[4]q
  path      = %[5]q
  sol_speed = "invalid"
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
					imageName,
					imagePath,
				),
				ExpectError: regexp.MustCompile(`Attribute sol_speed value must be one of`),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_InvalidPath(t *testing.T) {
	imageName := generateUniqueTestName("test-invalid-path")

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name = %[4]q
  path = "invalid-path-without-slash"
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
					imageName,
				),
				ExpectError: regexp.MustCompile(`path must match format: \/cm\/images\/name`),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_UnknownValue(t *testing.T) {
	imageName1 := generateUniqueTestName("test-base-image")
	imagePath1 := fmt.Sprintf("/cm/images/%s", imageName1)
	imageName2 := generateUniqueTestName("test-cloned-image")
	imagePath2 := fmt.Sprintf("/cm/images/%s", imageName2)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName1, imageName2)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				// Step 1: Create base image and clone it using resource reference
				// This introduces Unknown value during plan phase for original_image
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

# Lookup default-image to use as base for first clone
data "bcm_cmpart_softwareimages" "default" {}

locals {
  default_image = [for img in data.bcm_cmpart_softwareimages.default.images : img if img.name == "default-image"][0]
}

# Create base image by cloning default-image
resource "bcm_cmpart_softwareimage" "base" {
  name = %[4]q
  path = %[5]q

  # Clone from default-image (kernel_version inherited)
  original_image = local.default_image.uuid
}

# Clone using resource reference (original_image is Unknown during plan)
# This is the key test: bcm_cmpart_softwareimage.base.uuid is Unknown during plan
resource "bcm_cmpart_softwareimage" "cloned" {
  name           = %[6]q
  path           = %[7]q

  # This creates Unknown value during plan phase
  original_image = bcm_cmpart_softwareimage.base.uuid
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
					imageName1,
					imagePath1,
					imageName2,
					imagePath2,
				),
				ConfigStateChecks: []statecheck.StateCheck{
					// Verify base image was created
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.base",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName1),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.base",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
					// Verify cloned image was created with Unknown value resolution
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.cloned",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName2),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.cloned",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
				},
			},
		},
	})
}

// NOTE: Invalid/non-existent original_image UUID test removed
// BCM Behavior: BCM treats original_image as optional and creates image without cloning
// if the UUID doesn't exist or is invalid. This is permissive API behavior, not an error.
// The UnknownValue test above covers the important scenario of Unknown resolution.

// Phase 2 RED tests complete (including negative tests and edge cases)
// All tests should fail with "resource type not found", validation errors, or API errors

// ========================================
// Phase 3: Drift Detection Tests
// ========================================

// TestAccCMPartSoftwareImage_DriftKernelParameters tests drift detection for kernel_parameters attribute
// Phase 3 - Task T011 (RED): This test should FAIL initially (no PreConfig implementation yet)
func TestAccCMPartSoftwareImage_DriftKernelParameters(t *testing.T) {
	imageName := generateUniqueTestName("test-drift-kernel")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Step 1: Create resource with initial kernel_parameters
			{
				Config: testAccCMPartSoftwareImageResourceConfig_DriftKernel(imageName, imagePath, "quiet splash"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_parameters"),
						knownvalue.StringExact("quiet splash"),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
				},
			},
			// Step 2: Modify kernel_parameters externally via BCM API, verify drift detected
			{
				PreConfig: func() {
					// Phase 3 - Task T013 (GREEN): Implement PreConfig to modify via BCM API
					client := createTestBCMClient(t)
					ctx := context.Background()

					// Get UUID by image name using helper
					uuid := getResourceUUIDByName(t, "CMPart", "getSoftwareImage", imageName)

					// Fetch full software image data from BCM API
					body, err := client.CallJSONRPC(ctx, "CMPart", "getSoftwareImage", imageName)
					if err != nil {
						t.Fatalf("Failed to fetch software image for drift modification: %v", err)
					}

					// Parse the image data
					var imageData map[string]interface{}
					if err := json.Unmarshal(body, &imageData); err != nil {
						t.Fatalf("Failed to parse image data: %v", err)
					}

					// Modify kernelParameters (note: BCM uses camelCase, Terraform uses snake_case)
					imageData["kernelParameters"] = "quiet splash nomodeset"

					// Wrap in BCM API entity structure required for updates
					entity := map[string]interface{}{
						"baseType":      "SoftwareImage",
						"childType":     "",
						"modified":      true,
						"to_be_removed": false,
						"revision":      "",
						"uuid":          uuid,
					}
					// Copy all image data fields except uuid (already set above)
					for k, v := range imageData {
						if k != "uuid" {
							entity[k] = v
						}
					}

					// Update via BCM API (second parameter: clone = false)
					_, err = client.CallJSONRPC(ctx, "CMPart", "updateSoftwareImage", entity, false)
					if err != nil {
						t.Fatalf("Failed to update software image via BCM API: %v", err)
					}

					// Wait for eventual consistency
					time.Sleep(2 * time.Second)

					t.Logf("[DEBUG] Modified kernel_parameters externally to: %v", entity["kernelParameters"])
				},
				Config: testAccCMPartSoftwareImageResourceConfig_DriftKernel(imageName, imagePath, "quiet splash"),
				// Use ConfigPlanChecks to verify drift detected (non-empty plan expected)
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectNonEmptyPlan(),
					},
				},
			},
			// Step 3: Restore desired state (Terraform applies config to fix drift)
			{
				Config: testAccCMPartSoftwareImageResourceConfig_DriftKernel(imageName, imagePath, "quiet splash"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_parameters"),
						knownvalue.StringExact("quiet splash"),
					),
				},
			},
		},
	})
}

// TestAccCMPartSoftwareImage_Drift tests drift detection for notes attribute
// This test verifies that Terraform can detect and correct configuration drift
// when the notes field is modified externally via the BCM API
func TestAccCMPartSoftwareImage_Drift(t *testing.T) {
	imageName := generateUniqueTestName("test-drift-notes")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Step 1: Create resource with initial notes value
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Drift(imageName, imagePath, "Production environment"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("notes"),
						knownvalue.StringExact("Production environment"),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
				},
			},
			// Step 2: Modify notes externally via BCM API, verify drift detected
			{
				PreConfig: func() {
					client := createTestBCMClient(t)
					ctx := context.Background()

					// Get UUID by image name using helper
					uuid := getResourceUUIDByName(t, "CMPart", "getSoftwareImage", imageName)

					// Fetch full software image data from BCM API
					body, err := client.CallJSONRPC(ctx, "CMPart", "getSoftwareImage", imageName)
					if err != nil {
						t.Fatalf("Failed to fetch software image for drift modification: %v", err)
					}

					// Parse the image data
					var imageData map[string]interface{}
					if err := json.Unmarshal(body, &imageData); err != nil {
						t.Fatalf("Failed to parse image data: %v", err)
					}

					// Modify notes field (BCM uses same field name as Terraform)
					imageData["notes"] = "Staging environment"

					// Wrap in BCM API entity structure required for updates
					entity := map[string]interface{}{
						"baseType":      "SoftwareImage",
						"childType":     "",
						"modified":      true,
						"to_be_removed": false,
						"revision":      "",
						"uuid":          uuid,
					}
					// Copy all image data fields except uuid (already set above)
					for k, v := range imageData {
						if k != "uuid" {
							entity[k] = v
						}
					}

					// Update via BCM API (second parameter: clone = false)
					_, err = client.CallJSONRPC(ctx, "CMPart", "updateSoftwareImage", entity, false)
					if err != nil {
						t.Fatalf("Failed to update software image via BCM API: %v", err)
					}

					// Wait for eventual consistency
					time.Sleep(2 * time.Second)

					t.Logf("[DEBUG] Modified notes externally to: %v", entity["notes"])
				},
				Config: testAccCMPartSoftwareImageResourceConfig_Drift(imageName, imagePath, "Production environment"),
				// Use ConfigPlanChecks to verify drift detected (non-empty plan expected)
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectNonEmptyPlan(),
					},
				},
			},
			// Step 3: Restore desired state (Terraform applies config to fix drift)
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Drift(imageName, imagePath, "Production environment"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("notes"),
						knownvalue.StringExact("Production environment"),
					),
				},
			},
		},
	})
}

// ========================================
// Phase 4: Destroy Edge Case Tests (User Story 2)
// ========================================

// TestAccCMPartSoftwareImage_DestroyIdempotent verifies destroy is idempotent
// Phase 4 - Task T019 (RED): This test should FAIL initially (need graceful handling of already-deleted resources)
func TestAccCMPartSoftwareImage_DestroyIdempotent(t *testing.T) {
	imageName := generateUniqueTestName("test-destroy-idempotent")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Step 1: Create resource
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
				},
			},
			// Step 2: Destroy happens automatically, then manually verify CheckDestroy handles already-deleted
			// Note: We can't easily test double-destroy in the TestCase flow, so we rely on
			// CheckDestroy being called and handling the already-deleted case gracefully
		},
	})

	// After test completes, manually call CheckDestroy again to verify idempotency
	// This simulates a second destroy attempt on an already-deleted resource
	t.Run("VerifyIdempotentDestroy", func(t *testing.T) {
		// Create a mock state with a deleted resource UUID
		mockState := &terraform.State{
			Modules: []*terraform.ModuleState{
				{
					Path: []string{"root"},
					Resources: map[string]*terraform.ResourceState{
						"bcm_cmpart_softwareimage.test": {
							Type: "bcm_cmpart_softwareimage",
							Primary: &terraform.InstanceState{
								ID: "nonexistent-uuid",
								Attributes: map[string]string{
									"uuid": "nonexistent-uuid",
									"name": imageName,
								},
							},
						},
					},
				},
			},
		}

		// Call CheckDestroy on a non-existent resource - should not error
		err := testAccCheckCMPartSoftwareImageDestroy(mockState)
		if err != nil {
			t.Errorf("CheckDestroy should be idempotent and not error on already-deleted resource: %v", err)
		}
	})
}

// TestAccCMPartSoftwareImage_DestroyExternalDelete verifies destroy handles externally deleted resources
// Phase 4 - Task T022: Create resource, delete via BCM API, verify Terraform destroy succeeds
func TestAccCMPartSoftwareImage_DestroyExternalDelete(t *testing.T) {
	imageName := generateUniqueTestName("test-destroy-external")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Step 1: Create resource
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
				},
			},
			// Step 2: Delete externally via BCM API, then let Terraform destroy
			{
				PreConfig: func() {
					// Delete the resource via BCM API before Terraform tries to destroy it
					client := createTestBCMClient(t)
					ctx := context.Background()

					// Delete via BCM API (removeSoftwareImages expects array of names)
					_, err := client.CallJSONRPC(ctx, "CMPart", "removeSoftwareImages", []string{imageName}, false)
					if err != nil {
						t.Logf("[WARN] Failed to delete image externally (may not exist): %v", err)
					}

					// Wait for eventual consistency
					time.Sleep(2 * time.Second)

					t.Logf("[DEBUG] Deleted image externally: %s", imageName)
				},
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				// Destroy will happen automatically after this step
				// CheckDestroy should pass even though resource was already deleted
			},
		},
	})
}

// Helper function for drift detection test configuration
// Phase 3 - Task T015: Config function with parameterized kernel_parameters
func testAccCMPartSoftwareImageResourceConfig_DriftKernel(name, path, kernelParams string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name               = %[4]q
  path               = %[5]q
  kernel_parameters  = %[6]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		kernelParams,
	)
}

// Helper function for drift detection test configuration (notes field)
// Config function with parameterized notes
func testAccCMPartSoftwareImageResourceConfig_Drift(name, path, notes string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name  = %[4]q
  path  = %[5]q
  notes = %[6]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		notes,
	)
}

// ========================================
// Test Helper Functions
// ========================================

func testAccCMPartSoftwareImageResourceConfig_Basic(name, path string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name = %[4]q
  path = %[5]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
	)
}

func testAccCMPartSoftwareImageResourceConfig_Updated(name, path string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name  = %[4]q
  path  = %[5]q
  notes = "Updated notes"
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
	)
}

func testAccCMPartSoftwareImageResourceConfig_Full(name, path string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name               = %[4]q
  path               = %[5]q
  kernel_parameters  = "quiet splash"
  notes              = "Test image with full configuration"
  enable_sol         = true
  sol_speed          = "115200"

  modules = [
    {
      name = "module1"
    },
    {
      name = "module2"
    }
  ]
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
	)
}

func testAccCMPartSoftwareImageResourceConfig_KernelParams(name, path, kernelParams string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name              = %[4]q
  path              = %[5]q
  kernel_parameters = %[6]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		kernelParams,
	)
}

func testAccCMPartSoftwareImageResourceConfig_Modules(name, path string, moduleCount int) string {
	modulesConfig := ""
	if moduleCount > 0 {
		modulesConfig = "modules = [\n"
		for i := 0; i < moduleCount; i++ {
			modulesConfig += fmt.Sprintf("    { name = \"module%d\" },\n", i+1)
		}
		modulesConfig += "  ]"
	}

	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name = %[4]q
  path = %[5]q
  %[6]s
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		modulesConfig,
	)
}

func testAccCMPartSoftwareImageResourceConfig_SOL(name, path string, enableSOL bool, solSpeed string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name       = %[4]q
  path       = %[5]q
  enable_sol = %[6]t
  sol_speed  = %[7]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		enableSOL,
		solSpeed,
	)
}

// testAccCheckCMPartSoftwareImageDestroy verifies that all software images have been destroyed
// Phase 2 - Task T005: Enhanced with logging, timeout, and detailed error messages
func testAccCheckCMPartSoftwareImageDestroy(s *terraform.State) error {
	client, err := NewBCMClient(
		context.Background(),
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		true, // insecure_skip_verify
		30,   // timeout
	)
	if err != nil {
		return fmt.Errorf("Failed to create BCM client for CheckDestroy: %v", err)
	}

	resourceCount := 0
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "bcm_cmpart_softwareimage" {
			continue
		}

		resourceCount++
		uuid := rs.Primary.Attributes["uuid"]
		if uuid == "" {
			continue // Resource was never created
		}

		// Create 10s timeout context for this API call
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		// Try to read the software image via BCM API
		body, err := client.CallJSONRPC(ctx, "CMPart", "getSoftwareImage", uuid)

		// If API returns error OR empty response, resource is deleted (success)
		if err != nil {
			// API error means resource doesn't exist (deleted successfully)
			continue
		}

		// Try to unmarshal response
		var imageData map[string]interface{}
		if err := json.Unmarshal(body, &imageData); err != nil {
			// Can't parse response, assume deleted
			continue
		}

		// If we got valid data back, resource still exists (failure)
		if len(imageData) > 0 {
			return fmt.Errorf("Software image still exists after destroy. UUID: %s, Response: %s", uuid, string(body))
		}
	}

	// Log summary
	if resourceCount > 0 {
		fmt.Printf("[DEBUG] CheckDestroy verified %d software image resources were deleted\n", resourceCount)
	}

	return nil
}

// testAccCMPartSoftwareImagePreCheck deletes leftover test resources before running tests
// Phase 2 - Task T006: Refactored to use shared verifyResourceDeleted helper
func testAccCMPartSoftwareImagePreCheck(t *testing.T, imageNames ...string) {
	testAccPreCheck(t) // Check environment variables

	// Create BCM client for cleanup
	client, err := NewBCMClient(
		context.Background(),
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		true, // insecure_skip_verify
		30,   // timeout
	)
	if err != nil {
		t.Fatalf("Failed to create BCM client for PreCheck: %v", err)
	}

	ctx := context.Background()

	// Delete each test image by name if it exists
	for _, imageName := range imageNames {
		// Use shared helper with 5 retries (standardized)
		deleted := verifyResourceDeleted(ctx, client, "CMPart", "removeSoftwareImages", imageName, 5)
		if deleted {
			t.Logf("[DEBUG] PreCheck cleaned up existing image: %s", imageName)
		}
	}
}
