// Code generated by HashiCorp. DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

func TestAccCMPartSoftwareImageResource_Basic(t *testing.T) {
	imageName := generateUniqueTestName("test-image")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "name", imageName),
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "path", imagePath),
					resource.TestCheckResourceAttrSet("bcm_cmpart_softwareimage.test", "uuid"),
					resource.TestCheckResourceAttrSet("bcm_cmpart_softwareimage.test", "creation_time"),
				),
			},
			// ImportState testing
			{
				ResourceName:      "bcm_cmpart_softwareimage.test",
				ImportState:       true,
				ImportStateVerify: true,
				// Ignore computed fields that change
				ImportStateVerifyIgnore: []string{"original_image"},
			},
			// Update and Read testing
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Updated(imageName, imagePath),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "name", imageName),
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "notes", "Updated notes"),
				),
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}

func TestAccCMPartSoftwareImageResource_FullConfig(t *testing.T) {
	imageName := generateUniqueTestName("test-full")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Full(imageName, imagePath),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "name", imageName),
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "path", imagePath),
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "kernel_parameters", "quiet splash"),
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "notes", "Test image with full configuration"),
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "enable_sol", "true"),
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "sol_speed", "115200"),
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "modules.#", "2"),
				),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_UpdateKernelConfig(t *testing.T) {
	imageName := generateUniqueTestName("test-kernel-update")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_KernelParams(imageName, imagePath, "quiet"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "kernel_parameters", "quiet"),
				),
			},
			{
				Config: testAccCMPartSoftwareImageResourceConfig_KernelParams(imageName, imagePath, "quiet splash"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "kernel_parameters", "quiet splash"),
				),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_UpdateModules(t *testing.T) {
	imageName := generateUniqueTestName("test-modules-update")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Modules(imageName, imagePath, 1),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "modules.#", "1"),
				),
			},
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Modules(imageName, imagePath, 2),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "modules.#", "2"),
				),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_UpdateSOL(t *testing.T) {
	imageName := generateUniqueTestName("test-sol-update")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_SOL(imageName, imagePath, false, "9600"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "enable_sol", "false"),
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "sol_speed", "9600"),
				),
			},
			{
				Config: testAccCMPartSoftwareImageResourceConfig_SOL(imageName, imagePath, true, "115200"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "enable_sol", "true"),
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "sol_speed", "115200"),
				),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_MissingRequired(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: `
provider "bcm" {
  endpoint             = "https://172.21.15.254:8081"
  username             = "root"
  password             = "Hashicorp123!"
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  # Missing required name and path
}
`,
				ExpectError: regexp.MustCompile(`The argument "name" is required`),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_InvalidSOLSpeed(t *testing.T) {
	imageName := generateUniqueTestName("test-invalid-sol")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name      = %[4]q
  path      = %[5]q
  sol_speed = "invalid"
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
					imageName,
					imagePath,
				),
				ExpectError: regexp.MustCompile(`Attribute sol_speed value must be one of`),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_InvalidPath(t *testing.T) {
	imageName := generateUniqueTestName("test-invalid-path")

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name = %[4]q
  path = "invalid-path-without-slash"
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
					imageName,
				),
				ExpectError: regexp.MustCompile(`Attribute path.*must start with /`),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_UnknownValue(t *testing.T) {
	imageName1 := generateUniqueTestName("test-base-image")
	imagePath1 := fmt.Sprintf("/cm/images/%s", imageName1)
	imageName2 := generateUniqueTestName("test-cloned-image")
	imagePath2 := fmt.Sprintf("/cm/images/%s", imageName2)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName1, imageName2)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				// Step 1: Create base image and clone it using resource reference
				// This introduces Unknown value during plan phase for original_image
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

# Lookup default-image to use as base for first clone
data "bcm_cmpart_softwareimages" "default" {}

locals {
  default_image = [for img in data.bcm_cmpart_softwareimages.default.images : img if img.name == "default-image"][0]
}

# Create base image by cloning default-image
resource "bcm_cmpart_softwareimage" "base" {
  name = %[4]q
  path = %[5]q

  # Clone from default-image (kernel_version inherited)
  original_image = local.default_image.uuid
}

# Clone using resource reference (original_image is Unknown during plan)
# This is the key test: bcm_cmpart_softwareimage.base.uuid is Unknown during plan
resource "bcm_cmpart_softwareimage" "cloned" {
  name           = %[6]q
  path           = %[7]q

  # This creates Unknown value during plan phase
  original_image = bcm_cmpart_softwareimage.base.uuid
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
					imageName1,
					imagePath1,
					imageName2,
					imagePath2,
				),
				Check: resource.ComposeAggregateTestCheckFunc(
					// Verify base image was created
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.base", "name", imageName1),
					resource.TestCheckResourceAttrSet("bcm_cmpart_softwareimage.base", "uuid"),

					// Verify cloned image was created with Unknown value resolution
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.cloned", "name", imageName2),
					resource.TestCheckResourceAttrSet("bcm_cmpart_softwareimage.cloned", "uuid"),

					// Most importantly: verify that the cloned image has a UUID
					// This proves Unknown value was resolved during apply
					func(s *terraform.State) error {
						rs, ok := s.RootModule().Resources["bcm_cmpart_softwareimage.cloned"]
						if !ok {
							return fmt.Errorf("Resource not found: bcm_cmpart_softwareimage.cloned")
						}

						if rs.Primary.Attributes["uuid"] == "" {
							return fmt.Errorf("UUID should be set after Unknown value resolution")
						}

						return nil
					},
				),
			},
		},
	})
}

// NOTE: Invalid/non-existent original_image UUID test removed
// BCM Behavior: BCM treats original_image as optional and creates image without cloning
// if the UUID doesn't exist or is invalid. This is permissive API behavior, not an error.
// The UnknownValue test above covers the important scenario of Unknown resolution.

// Phase 2 RED tests complete (including negative tests and edge cases)
// All tests should fail with "resource type not found", validation errors, or API errors

// ========================================
// Phase 3: Drift Detection Tests
// ========================================

// TestAccCMPartSoftwareImage_DriftKernelParameters tests drift detection for kernel_parameters attribute
// Phase 3 - Task T011 (RED): This test should FAIL initially (no PreConfig implementation yet)
func TestAccCMPartSoftwareImage_DriftKernelParameters(t *testing.T) {
	imageName := generateUniqueTestName("test-drift-kernel")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Step 1: Create resource with initial kernel_parameters
			{
				Config: testAccCMPartSoftwareImageResourceConfig_DriftKernel(imageName, imagePath, "quiet splash"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "name", imageName),
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "kernel_parameters", "quiet splash"),
					resource.TestCheckResourceAttrSet("bcm_cmpart_softwareimage.test", "uuid"),
				),
			},
			// Step 2: Modify kernel_parameters externally via BCM API, verify drift detected
			{
				PreConfig: func() {
					// TODO T013: Implement PreConfig to modify via BCM API
					// This will:
					// 1. Create BCM client with createTestBCMClient(t)
					// 2. Query BCM API to get UUID by image name
					// 3. Call updateSoftwareImage API to change kernelParameters to "quiet splash nomodeset"
					// For now, this will fail with "no PreConfig logic implemented"
				},
				Config: testAccCMPartSoftwareImageResourceConfig_DriftKernel(imageName, imagePath, "quiet splash"),
				Check: resource.ComposeAggregateTestCheckFunc(
					// After external modification, Terraform should detect drift
					// State should reflect the BCM API value (modified value)
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "kernel_parameters", "quiet splash nomodeset"),
				),
				// CRITICAL: This tells Terraform we expect the plan to be non-empty
				// because drift was detected
				ExpectNonEmptyPlan: true,
			},
			// Step 3: Restore desired state (Terraform applies config to fix drift)
			{
				Config: testAccCMPartSoftwareImageResourceConfig_DriftKernel(imageName, imagePath, "quiet splash"),
				Check: resource.ComposeAggregateTestCheckFunc(
					// Verify drift was corrected and state matches config
					resource.TestCheckResourceAttr("bcm_cmpart_softwareimage.test", "kernel_parameters", "quiet splash"),
				),
			},
		},
	})
}

// Helper function for drift detection test configuration
// Phase 3 - Task T015: Config function with parameterized kernel_parameters
func testAccCMPartSoftwareImageResourceConfig_DriftKernel(name, path, kernelParams string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name               = %[4]q
  path               = %[5]q
  kernel_parameters  = %[6]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		kernelParams,
	)
}

// ========================================
// Test Helper Functions
// ========================================

func testAccCMPartSoftwareImageResourceConfig_Basic(name, path string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name = %[4]q
  path = %[5]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
	)
}

func testAccCMPartSoftwareImageResourceConfig_Updated(name, path string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name  = %[4]q
  path  = %[5]q
  notes = "Updated notes"
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
	)
}

func testAccCMPartSoftwareImageResourceConfig_Full(name, path string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name               = %[4]q
  path               = %[5]q
  kernel_parameters  = "quiet splash"
  notes              = "Test image with full configuration"
  enable_sol         = true
  sol_speed          = "115200"

  modules = [
    {
      name = "module1"
    },
    {
      name = "module2"
    }
  ]
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
	)
}

func testAccCMPartSoftwareImageResourceConfig_KernelParams(name, path, kernelParams string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name              = %[4]q
  path              = %[5]q
  kernel_parameters = %[6]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		kernelParams,
	)
}

func testAccCMPartSoftwareImageResourceConfig_Modules(name, path string, moduleCount int) string {
	modulesConfig := ""
	if moduleCount > 0 {
		modulesConfig = "modules = [\n"
		for i := 0; i < moduleCount; i++ {
			modulesConfig += fmt.Sprintf("    { name = \"module%d\" },\n", i+1)
		}
		modulesConfig += "  ]"
	}

	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name = %[4]q
  path = %[5]q
  %[6]s
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		modulesConfig,
	)
}

func testAccCMPartSoftwareImageResourceConfig_SOL(name, path string, enableSOL bool, solSpeed string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name       = %[4]q
  path       = %[5]q
  enable_sol = %[6]t
  sol_speed  = %[7]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		enableSOL,
		solSpeed,
	)
}

// testAccCheckCMPartSoftwareImageDestroy verifies that all software images have been destroyed
// Phase 2 - Task T005: Enhanced with logging, timeout, and detailed error messages
func testAccCheckCMPartSoftwareImageDestroy(s *terraform.State) error {
	client, err := NewBCMClient(
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		true, // insecure_skip_verify
	)
	if err != nil {
		return fmt.Errorf("Failed to create BCM client for CheckDestroy: %v", err)
	}

	resourceCount := 0
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "bcm_cmpart_softwareimage" {
			continue
		}

		resourceCount++
		uuid := rs.Primary.Attributes["uuid"]
		if uuid == "" {
			continue // Resource was never created
		}

		// Create 10s timeout context for this API call
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		// Try to read the software image via BCM API
		body, err := client.CallJSONRPC(ctx, "CMPart", "getSoftwareImage", uuid)

		// If API returns error OR empty response, resource is deleted (success)
		if err != nil {
			// API error means resource doesn't exist (deleted successfully)
			continue
		}

		// Try to unmarshal response
		var imageData map[string]interface{}
		if err := json.Unmarshal(body, &imageData); err != nil {
			// Can't parse response, assume deleted
			continue
		}

		// If we got valid data back, resource still exists (failure)
		if len(imageData) > 0 {
			return fmt.Errorf("Software image still exists after destroy. UUID: %s, Response: %s", uuid, string(body))
		}
	}

	// Log summary
	if resourceCount > 0 {
		fmt.Printf("[DEBUG] CheckDestroy verified %d software image resources were deleted\n", resourceCount)
	}

	return nil
}

// testAccCMPartSoftwareImagePreCheck deletes leftover test resources before running tests
// Phase 2 - Task T006: Refactored to use shared verifyResourceDeleted helper
func testAccCMPartSoftwareImagePreCheck(t *testing.T, imageNames ...string) {
	testAccPreCheck(t) // Check environment variables

	// Create BCM client for cleanup
	client, err := NewBCMClient(
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		true,
	)
	if err != nil {
		t.Fatalf("Failed to create BCM client for PreCheck: %v", err)
	}

	ctx := context.Background()

	// Delete each test image by name if it exists
	for _, imageName := range imageNames {
		// Use shared helper with 5 retries (standardized)
		deleted, err := verifyResourceDeleted(ctx, client, "CMPart", "removeSoftwareImages", imageName, 5)
		if err != nil {
			t.Logf("[WARN] PreCheck cleanup error for image %s: %v", imageName, err)
		}
		if deleted {
			t.Logf("[DEBUG] PreCheck cleaned up existing image: %s", imageName)
		}
	}
}
