// Code generated by HashiCorp. DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/compare"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
)

func TestAccCMPartSoftwareImageResource_Basic(t *testing.T) {
	imageName := generateUniqueTestName("tftest-image")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	// ID consistency tracking across all CRUD operations
	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Create and Read testing
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					// Modern state verification with type-safe matchers
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("path"),
						knownvalue.StringExact(imagePath),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
						knownvalue.NotNull(),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("creation_time"),
						knownvalue.NotNull(),
					),
					// Track ID for consistency across operations
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check after Create
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// ImportState testing
			{
				ResourceName:      "bcm_cmpart_softwareimage.test",
				ImportState:       true,
				ImportStateVerify: true,
				// Ignore computed fields that change
				ImportStateVerifyIgnore: []string{
					"original_image", // Computed field for cloning - not returned by BCM after clone
					"force",          // Action parameter - not persisted in BCM state
				},
			},
			// Update and Read testing
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Updated(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("notes"),
						knownvalue.StringExact("Updated notes"),
					),
					// Verify ID unchanged after update
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check after Update
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Updated(imageName, imagePath),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}

func TestAccCMPartSoftwareImageResource_FullConfig(t *testing.T) {
	imageName := generateUniqueTestName("tftest-full")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	// ID consistency tracking across test steps
	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Full(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("path"),
						knownvalue.StringExact(imagePath),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_parameters"),
						knownvalue.StringExact("quiet splash"),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("notes"),
						knownvalue.StringExact("Test image with full configuration"),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("enable_sol"),
						knownvalue.Bool(true),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("sol_speed"),
						knownvalue.StringExact("115200"),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("modules"),
						knownvalue.ListSizeExact(2),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Full(imageName, imagePath),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_UpdateKernelConfig(t *testing.T) {
	imageName := generateUniqueTestName("tftest-kernel-update")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	// ID consistency tracking across test steps
	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_KernelParams(imageName, imagePath, "quiet"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_parameters"),
						knownvalue.StringExact("quiet"),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			{
				Config: testAccCMPartSoftwareImageResourceConfig_KernelParams(imageName, imagePath, "quiet splash"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_parameters"),
						knownvalue.StringExact("quiet splash"),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check after update
			{
				Config: testAccCMPartSoftwareImageResourceConfig_KernelParams(imageName, imagePath, "quiet splash"),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_UpdateModules(t *testing.T) {
	imageName := generateUniqueTestName("tftest-modules-update")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	// ID consistency tracking across test steps
	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Modules(imageName, imagePath, 1),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("modules"),
						knownvalue.ListSizeExact(1),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Modules(imageName, imagePath, 2),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("modules"),
						knownvalue.ListSizeExact(2),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check after update
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Modules(imageName, imagePath, 2),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_UpdateSOL(t *testing.T) {
	imageName := generateUniqueTestName("tftest-sol-update")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	// ID consistency tracking across test steps
	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_SOL(imageName, imagePath, false, "9600"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("enable_sol"),
						knownvalue.Bool(false),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("sol_speed"),
						knownvalue.StringExact("9600"),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			{
				Config: testAccCMPartSoftwareImageResourceConfig_SOL(imageName, imagePath, true, "115200"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("enable_sol"),
						knownvalue.Bool(true),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("sol_speed"),
						knownvalue.StringExact("115200"),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check after update
			{
				Config: testAccCMPartSoftwareImageResourceConfig_SOL(imageName, imagePath, true, "115200"),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_ValidationInvalidName(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  # Missing required name and path
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
				),
				ExpectError: regexp.MustCompile(`The argument "name" is required`),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_InvalidSOLSpeed(t *testing.T) {
	imageName := generateUniqueTestName("tftest-invalid-sol")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name      = %[4]q
  path      = %[5]q
  sol_speed = "invalid"
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
					imageName,
					imagePath,
				),
				ExpectError: regexp.MustCompile(`Attribute sol_speed value must be one of`),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_InvalidPath(t *testing.T) {
	imageName := generateUniqueTestName("tftest-invalid-path")

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name = %[4]q
  path = "invalid-path-without-slash"
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
					imageName,
				),
				ExpectError: regexp.MustCompile(`path must match format: \/cm\/images\/name`),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_InvalidModules(t *testing.T) {
	imageName := generateUniqueTestName("tftest-invalid-modules")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name = %[4]q
  path = %[5]q

  modules = [
    {
      name = ""  # Empty module name should fail validation
    }
  ]
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
					imageName,
					imagePath,
				),
				ExpectError: regexp.MustCompile(`Attribute modules\[0\]\.name string length must be at least 1`),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_ValidationInvalidSOLPort(t *testing.T) {
	imageName := generateUniqueTestName("tftest-invalid-solport")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name     = %[4]q
  path     = %[5]q
  sol_port = "invalid"
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
					imageName,
					imagePath,
				),
				ExpectError: regexp.MustCompile(`Attribute sol_port value must be one of`),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_ValidationEmptyModuleName(t *testing.T) {
	imageName := generateUniqueTestName("tftest-empty-modname")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name = %[4]q
  path = %[5]q

  modules = [
    {
      name = ""
    }
  ]
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
					imageName,
					imagePath,
				),
				ExpectError: regexp.MustCompile(`Attribute modules\[0\]\.name string length must be at least 1`),
			},
		},
	})
}

func TestAccCMPartSoftwareImageResource_UnknownValue(t *testing.T) {
	imageName1 := generateUniqueTestName("tftest-base-image")
	imagePath1 := fmt.Sprintf("/cm/images/%s", imageName1)
	imageName2 := generateUniqueTestName("tftest-cloned-image")
	imagePath2 := fmt.Sprintf("/cm/images/%s", imageName2)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName1, imageName2)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				// Step 1: Create base image and clone it using resource reference
				// This introduces Unknown value during plan phase for original_image
				Config: fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

# Lookup default-image to use as base for first clone
data "bcm_cmpart_softwareimages" "default" {}

locals {
  default_image = [for img in data.bcm_cmpart_softwareimages.default.images : img if img.name == "default-image"][0]
}

# Create base image by cloning default-image
resource "bcm_cmpart_softwareimage" "base" {
  name = %[4]q
  path = %[5]q

  # Clone from default-image (kernel_version inherited)
  original_image = local.default_image.uuid
}

# Clone using resource reference (original_image is Unknown during plan)
# This is the key test: bcm_cmpart_softwareimage.base.uuid is Unknown during plan
resource "bcm_cmpart_softwareimage" "cloned" {
  name           = %[6]q
  path           = %[7]q

  # This creates Unknown value during plan phase
  original_image = bcm_cmpart_softwareimage.base.uuid
}
`,
					os.Getenv("BCM_ENDPOINT"),
					os.Getenv("BCM_USERNAME"),
					os.Getenv("BCM_PASSWORD"),
					imageName1,
					imagePath1,
					imageName2,
					imagePath2,
				),
				ConfigStateChecks: []statecheck.StateCheck{
					// Verify base image was created
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.base",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName1),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.base",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
					// Verify cloned image was created with Unknown value resolution
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.cloned",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName2),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.cloned",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
				},
			},
		},
	})
}

// NOTE: Invalid/non-existent original_image UUID test removed
// BCM Behavior: BCM treats original_image as optional and creates image without cloning
// if the UUID doesn't exist or is invalid. This is permissive API behavior, not an error.
// The UnknownValue test above covers the important scenario of Unknown resolution.

// Phase 2 RED tests complete (including negative tests and edge cases)
// All tests should fail with "resource type not found", validation errors, or API errors

// ========================================
// Phase 3: Drift Detection Tests
// ========================================

// TestAccCMPartSoftwareImage_DriftKernelParameters tests drift detection for kernel_parameters attribute
// Phase 3 - Task T011 (RED): This test should FAIL initially (no PreConfig implementation yet)
func TestAccCMPartSoftwareImage_DriftKernelParameters(t *testing.T) {
	imageName := generateUniqueTestName("tftest-drift-kernel")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	// ID consistency tracking across test steps
	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Step 1: Create resource with initial kernel_parameters
			{
				Config: testAccCMPartSoftwareImageResourceConfig_DriftKernel(imageName, imagePath, "quiet splash"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_parameters"),
						knownvalue.StringExact("quiet splash"),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Step 2: Modify kernel_parameters externally via BCM API, verify drift detected
			{
				PreConfig: func() {
					// Phase 3 - Task T013 (GREEN): Implement PreConfig to modify via BCM API
					client := createTestBCMClient(t)
					ctx := context.Background()

					// Get UUID by image name using helper
					uuid := getResourceUUIDByName(t, "CMPart", "getSoftwareImage", imageName)

					// Fetch full software image data from BCM API
					body, err := client.CallJSONRPC(ctx, "CMPart", "getSoftwareImage", imageName)
					if err != nil {
						t.Fatalf("Failed to fetch software image for drift modification: %v", err)
					}

					// Parse the image data
					var imageData map[string]interface{}
					if err := json.Unmarshal(body, &imageData); err != nil {
						t.Fatalf("Failed to parse image data: %v", err)
					}

					// Modify kernelParameters (note: BCM uses camelCase, Terraform uses snake_case)
					imageData["kernelParameters"] = "quiet splash nomodeset"

					// Wrap in BCM API entity structure required for updates
					entity := map[string]interface{}{
						"baseType":      "SoftwareImage",
						"childType":     "",
						"modified":      true,
						"to_be_removed": false,
						"revision":      "",
						"uuid":          uuid,
					}
					// Copy all image data fields except uuid (already set above)
					for k, v := range imageData {
						if k != "uuid" {
							entity[k] = v
						}
					}

					// Update via BCM API (second parameter: clone = false)
					_, err = client.CallJSONRPC(ctx, "CMPart", "updateSoftwareImage", entity, false)
					if err != nil {
						t.Fatalf("Failed to update software image via BCM API: %v", err)
					}

					// Wait for eventual consistency
					time.Sleep(TestEventualConsistencyDelay)

					t.Logf("[DEBUG] Modified kernel_parameters externally to: %v", entity["kernelParameters"])
				},
				Config: testAccCMPartSoftwareImageResourceConfig_DriftKernel(imageName, imagePath, "quiet splash"),
				// Use ConfigPlanChecks to verify drift detected (non-empty plan expected)
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectNonEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Step 3: Restore desired state (Terraform applies config to fix drift)
			{
				Config: testAccCMPartSoftwareImageResourceConfig_DriftKernel(imageName, imagePath, "quiet splash"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_parameters"),
						knownvalue.StringExact("quiet splash"),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
		},
	})
}

// TestAccCMPartSoftwareImage_Drift tests drift detection for notes attribute
// This test verifies that Terraform can detect and correct configuration drift
// when the notes field is modified externally via the BCM API
func TestAccCMPartSoftwareImage_Drift(t *testing.T) {
	imageName := generateUniqueTestName("tftest-drift-notes")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	// ID consistency tracking across test steps
	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Step 1: Create resource with initial notes value
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Drift(imageName, imagePath, "Production environment"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("notes"),
						knownvalue.StringExact("Production environment"),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Step 2: Modify notes externally via BCM API, verify drift detected
			{
				PreConfig: func() {
					client := createTestBCMClient(t)
					ctx := context.Background()

					// Get UUID by image name using helper
					uuid := getResourceUUIDByName(t, "CMPart", "getSoftwareImage", imageName)

					// Fetch full software image data from BCM API
					body, err := client.CallJSONRPC(ctx, "CMPart", "getSoftwareImage", imageName)
					if err != nil {
						t.Fatalf("Failed to fetch software image for drift modification: %v", err)
					}

					// Parse the image data
					var imageData map[string]interface{}
					if err := json.Unmarshal(body, &imageData); err != nil {
						t.Fatalf("Failed to parse image data: %v", err)
					}

					// Modify notes field (BCM uses same field name as Terraform)
					imageData["notes"] = "Staging environment"

					// Wrap in BCM API entity structure required for updates
					entity := map[string]interface{}{
						"baseType":      "SoftwareImage",
						"childType":     "",
						"modified":      true,
						"to_be_removed": false,
						"revision":      "",
						"uuid":          uuid,
					}
					// Copy all image data fields except uuid (already set above)
					for k, v := range imageData {
						if k != "uuid" {
							entity[k] = v
						}
					}

					// Update via BCM API (second parameter: clone = false)
					_, err = client.CallJSONRPC(ctx, "CMPart", "updateSoftwareImage", entity, false)
					if err != nil {
						t.Fatalf("Failed to update software image via BCM API: %v", err)
					}

					// Wait for eventual consistency
					time.Sleep(TestEventualConsistencyDelay)

					t.Logf("[DEBUG] Modified notes externally to: %v", entity["notes"])
				},
				Config: testAccCMPartSoftwareImageResourceConfig_Drift(imageName, imagePath, "Production environment"),
				// Use ConfigPlanChecks to verify drift detected (non-empty plan expected)
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectNonEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Step 3: Restore desired state (Terraform applies config to fix drift)
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Drift(imageName, imagePath, "Production environment"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("notes"),
						knownvalue.StringExact("Production environment"),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
		},
	})
}

// ========================================
// Phase 4: Destroy Edge Case Tests (User Story 2)
// ========================================

// TestAccCMPartSoftwareImage_DestroyIdempotent verifies destroy is idempotent
// Phase 4 - Task T019 (RED): This test should FAIL initially (need graceful handling of already-deleted resources)
func TestAccCMPartSoftwareImage_DestroyIdempotent(t *testing.T) {
	imageName := generateUniqueTestName("tftest-destroy-idempotent")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Step 1: Create resource
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
				},
			},
			// Step 2: Destroy happens automatically, then manually verify CheckDestroy handles already-deleted
			// Note: We can't easily test double-destroy in the TestCase flow, so we rely on
			// CheckDestroy being called and handling the already-deleted case gracefully
		},
	})

	// After test completes, manually call CheckDestroy again to verify idempotency
	// This simulates a second destroy attempt on an already-deleted resource
	t.Run("VerifyIdempotentDestroy", func(t *testing.T) {
		// Create a mock state with a deleted resource UUID
		mockState := &terraform.State{
			Modules: []*terraform.ModuleState{
				{
					Path: []string{"root"},
					Resources: map[string]*terraform.ResourceState{
						"bcm_cmpart_softwareimage.test": {
							Type: "bcm_cmpart_softwareimage",
							Primary: &terraform.InstanceState{
								ID: "nonexistent-uuid",
								Attributes: map[string]string{
									"uuid": "nonexistent-uuid",
									"name": imageName,
								},
							},
						},
					},
				},
			},
		}

		// Call CheckDestroy on a non-existent resource - should not error
		err := testAccCheckCMPartSoftwareImageDestroy(mockState)
		if err != nil {
			t.Errorf("CheckDestroy should be idempotent and not error on already-deleted resource: %v", err)
		}
	})
}

// TestAccCMPartSoftwareImage_DestroyExternalDelete verifies destroy handles externally deleted resources
// Phase 4 - Task T022: Create resource, delete via BCM API, verify Terraform destroy succeeds
func TestAccCMPartSoftwareImage_DestroyExternalDelete(t *testing.T) {
	imageName := generateUniqueTestName("tftest-destroy-external")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Step 1: Create resource
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("uuid"),
						knownvalue.NotNull(),
					),
				},
			},
			// Step 2: Delete externally via BCM API, then let Terraform destroy
			{
				PreConfig: func() {
					// Delete the resource via BCM API before Terraform tries to destroy it
					client := createTestBCMClient(t)
					ctx := context.Background()

					// Delete via BCM API (removeSoftwareImages expects array of names)
					_, err := client.CallJSONRPC(ctx, "CMPart", "removeSoftwareImages", []string{imageName}, false)
					if err != nil {
						t.Logf("[WARN] Failed to delete image externally (may not exist): %v", err)
					}

					// Wait for eventual consistency
					time.Sleep(TestEventualConsistencyDelay)

					t.Logf("[DEBUG] Deleted image externally: %s", imageName)
				},
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				// Destroy will happen automatically after this step
				// CheckDestroy should pass even though resource was already deleted
			},
		},
	})
}

// Helper function for drift detection test configuration
// Phase 3 - Task T015: Config function with parameterized kernel_parameters
func testAccCMPartSoftwareImageResourceConfig_DriftKernel(name, path, kernelParams string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name               = %[4]q
  path               = %[5]q
  kernel_parameters  = %[6]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		kernelParams,
	)
}

// Helper function for drift detection test configuration (notes field)
// Config function with parameterized notes
func testAccCMPartSoftwareImageResourceConfig_Drift(name, path, notes string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name  = %[4]q
  path  = %[5]q
  notes = %[6]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		notes,
	)
}

// ========================================
// Test Helper Functions
// ========================================

func testAccCMPartSoftwareImageResourceConfig_Basic(name, path string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name = %[4]q
  path = %[5]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
	)
}

func testAccCMPartSoftwareImageResourceConfig_Updated(name, path string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name  = %[4]q
  path  = %[5]q
  notes = "Updated notes"
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
	)
}

func testAccCMPartSoftwareImageResourceConfig_Full(name, path string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name               = %[4]q
  path               = %[5]q
  kernel_parameters  = "quiet splash"
  notes              = "Test image with full configuration"
  enable_sol         = true
  sol_speed          = "115200"

  modules = [
    {
      name = "module1"
    },
    {
      name = "module2"
    }
  ]
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
	)
}

func testAccCMPartSoftwareImageResourceConfig_KernelParams(name, path, kernelParams string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name              = %[4]q
  path              = %[5]q
  kernel_parameters = %[6]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		kernelParams,
	)
}

func testAccCMPartSoftwareImageResourceConfig_Modules(name, path string, moduleCount int) string {
	modulesConfig := ""
	if moduleCount > 0 {
		modulesConfig = "modules = [\n"
		for i := 0; i < moduleCount; i++ {
			modulesConfig += fmt.Sprintf("    { name = \"module%d\" },\n", i+1)
		}
		modulesConfig += "  ]"
	}

	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name = %[4]q
  path = %[5]q
  %[6]s
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		modulesConfig,
	)
}

func testAccCMPartSoftwareImageResourceConfig_SOL(name, path string, enableSOL bool, solSpeed string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name       = %[4]q
  path       = %[5]q
  enable_sol = %[6]t
  sol_speed  = %[7]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		enableSOL,
		solSpeed,
	)
}

// testAccCheckCMPartSoftwareImageDestroy verifies that all software images have been destroyed
// Enhanced with logging, timeout, detailed error messages, and dependency-aware cleanup handling.
// Note: Software images may still exist if referenced by categories - this is not a test failure,
// as the proper cleanup order is: devices → categories → software images.
func testAccCheckCMPartSoftwareImageDestroy(s *terraform.State) error {
	client := createTestBCMClient(&testing.T{})
	ctx := context.Background()

	resourceCount := 0
	var errors []string

	for _, rs := range s.RootModule().Resources {
		if rs.Type != "bcm_cmpart_softwareimage" {
			continue
		}

		resourceCount++
		imageName := rs.Primary.Attributes["name"]
		uuid := rs.Primary.Attributes["uuid"]
		if uuid == "" {
			continue // Resource was never created
		}

		// Verify software image deleted with exponential backoff (4 retries)
		deleted := verifyResourceDeleted(
			ctx,
			client,
			"CMPart",
			"getSoftwareImage",
			uuid,
			4, // retry count with exponential backoff
		)

		if !deleted {
			// Image still exists - check if it's referenced by categories
			result, checkErr := CheckCategoriesUsingImage(ctx, client, imageName)
			if checkErr == nil && result.HasDependencies {
				// Image still exists because it's referenced by categories
				// This is expected - categories must be deleted first (proper cleanup order)
				fmt.Printf("[DEBUG] Software image '%s' still exists but is referenced by %d category/categories - this is expected during test cleanup\n",
					imageName, result.DependentCount)
				continue
			}

			// Image exists but has no dependencies - this is a test failure
			errors = append(errors, fmt.Sprintf(
				"Software image '%s' still exists after destroy with no dependencies. UUID: %s, Retries: 4",
				imageName, uuid))
		}
	}

	if len(errors) > 0 {
		return fmt.Errorf("CheckDestroy failures:\n  - %s\n  - Verified: %d software images",
			strings.Join(errors, "\n  - "),
			resourceCount)
	}

	// Log summary
	if resourceCount > 0 {
		fmt.Printf("[DEBUG] CheckDestroy verified %d software image resources were deleted or have valid dependencies\n", resourceCount)
	}

	return nil
}

// testAccCMPartSoftwareImagePreCheck deletes leftover test resources before running tests
// Phase 2 - Task T006: Refactored to use shared verifyResourceDeleted helper
func testAccCMPartSoftwareImagePreCheck(t *testing.T, imageNames ...string) {
	testAccPreCheck(t) // Check environment variables

	// Create BCM client for cleanup
	client, err := NewBCMClient(
		context.Background(),
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		true, // insecure_skip_verify
		30,   // timeout
	)
	if err != nil {
		t.Fatalf("Failed to create BCM client for PreCheck: %v", err)
	}

	ctx := context.Background()

	// Delete each test image by name if it exists
	for _, imageName := range imageNames {
		// First attempt to delete the resource
		_, _ = client.CallJSONRPC(ctx, "CMPart", "removeSoftwareImages", []string{imageName}, false)
		// Give BCM time to process the deletion
		time.Sleep(TestEventualConsistencyDelay)
		// Then verify it's actually deleted using a GET method
		deleted := verifyResourceDeleted(ctx, client, "CMPart", "getSoftwareImage", imageName, 5)
		if deleted {
			t.Logf("[DEBUG] PreCheck cleaned up existing image: %s", imageName)
		}
	}
}

// TestAccCMPartSoftwareImageResource_SOLConfiguration tests Serial Over LAN advanced settings
func TestAccCMPartSoftwareImageResource_SOLConfiguration(t *testing.T) {
	imageName := generateUniqueTestName("tftest-sol-config")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	// ID consistency tracking across test steps
	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Create with SOL advanced configuration
			{
				Config: testAccCMPartSoftwareImageResourceConfig_SOLAdvanced(
					imageName,
					imagePath,
					"ttyS0",
					true,
				),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("sol_port"),
						knownvalue.StringExact("ttyS0"),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("sol_flow_control"),
						knownvalue.Bool(true),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Update SOL configuration
			{
				Config: testAccCMPartSoftwareImageResourceConfig_SOLAdvanced(
					imageName,
					imagePath,
					"ttyS1",
					false,
				),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("sol_port"),
						knownvalue.StringExact("ttyS1"),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("sol_flow_control"),
						knownvalue.Bool(false),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check
			{
				Config: testAccCMPartSoftwareImageResourceConfig_SOLAdvanced(
					imageName,
					imagePath,
					"ttyS1",
					false,
				),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
		},
	})
}

func testAccCMPartSoftwareImageResourceConfig_SOLAdvanced(name, path, solPort string, solFlowControl bool) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name             = %[4]q
  path             = %[5]q
  sol_port         = %[6]q
  sol_flow_control = %[7]t
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		solPort,
		solFlowControl,
	)
}

// TestAccCMPartSoftwareImageResource_KernelOutputConsole tests kernel_output_console field
func TestAccCMPartSoftwareImageResource_KernelOutputConsole(t *testing.T) {
	imageName := generateUniqueTestName("tftest-kernel-console")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	// ID consistency tracking across test steps
	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Create with default kernel_output_console (should be "tty0")
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_output_console"),
						knownvalue.StringExact("tty0"),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Update to custom kernel_output_console
			{
				Config: testAccCMPartSoftwareImageResourceConfig_KernelConsole(imageName, imagePath, "ttyS0"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_output_console"),
						knownvalue.StringExact("ttyS0"),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check
			{
				Config: testAccCMPartSoftwareImageResourceConfig_KernelConsole(imageName, imagePath, "ttyS0"),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Update to different kernel_output_console
			{
				Config: testAccCMPartSoftwareImageResourceConfig_KernelConsole(imageName, imagePath, "tty1"),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("kernel_output_console"),
						knownvalue.StringExact("tty1"),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
		},
	})
}

// TestAccCMPartSoftwareImageResource_ComputedFields verifies computed-only fields are populated
func TestAccCMPartSoftwareImageResource_ComputedFields(t *testing.T) {
	imageName := generateUniqueTestName("tftest-computed-fields")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Create and verify computed fields are populated
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					// Verify revision_id is computed and present (should be a number >= 0)
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("revision_id"),
						knownvalue.NotNull(),
					),
					// Verify file_operation_in_progress is computed and present
					// For a completed image creation, should be false
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("file_operation_in_progress"),
						knownvalue.Bool(false),
					),
					// Note: parent_software_image is only set when this is a revision
					// For a new (non-revision) image, we expect it to be null
					// We verify it exists in state but don't check the value
				},
			},
		},
	})
}

// TestAccCMPartSoftwareImageResource_ForceParameter tests the force parameter
func TestAccCMPartSoftwareImageResource_ForceParameter(t *testing.T) {
	imageName := generateUniqueTestName("tftest-force-param")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	// ID consistency tracking across test steps
	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Create with force = false (default)
			{
				Config: testAccCMPartSoftwareImageResourceConfig_ForceParameter(imageName, imagePath, false),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("force"),
						knownvalue.Bool(false),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check with force = false
			{
				Config: testAccCMPartSoftwareImageResourceConfig_ForceParameter(imageName, imagePath, false),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Update to force = true
			{
				Config: testAccCMPartSoftwareImageResourceConfig_ForceParameter(imageName, imagePath, true),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("force"),
						knownvalue.Bool(true),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check with force = true
			{
				Config: testAccCMPartSoftwareImageResourceConfig_ForceParameter(imageName, imagePath, true),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Update back to force = false
			{
				Config: testAccCMPartSoftwareImageResourceConfig_ForceParameter(imageName, imagePath, false),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("force"),
						knownvalue.Bool(false),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
		},
	})
}

// TestAccCMPartSoftwareImageResource_ForceParameterDefault tests that force defaults to false
func TestAccCMPartSoftwareImageResource_ForceParameterDefault(t *testing.T) {
	imageName := generateUniqueTestName("tftest-force-default")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Create without specifying force (should default to false)
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					// Verify force defaults to false when not specified
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("force"),
						knownvalue.Bool(false),
					),
				},
			},
		},
	})
}

func testAccCMPartSoftwareImageResourceConfig_ForceParameter(name, path string, force bool) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name  = %[4]q
  path  = %[5]q
  force = %[6]t
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		force,
	)
}

func testAccCMPartSoftwareImageResourceConfig_KernelConsole(name, path, kernelConsole string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

resource "bcm_cmpart_softwareimage" "test" {
  name                  = %[4]q
  path                  = %[5]q
  kernel_output_console = %[6]q
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
		kernelConsole,
	)
}

// TestAccCMPartSoftwareImageResource_BootFSPart tests bootfspart computed field
// This test verifies that the bootfspart field is properly populated when cloning images
func TestAccCMPartSoftwareImageResource_BootFSPart(t *testing.T) {
	imageName := generateUniqueTestName("tftest-bootfspart")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	// ID consistency tracking across test steps
	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			// Create with clone from default-image to populate bootfspart
			{
				Config: testAccCMPartSoftwareImageResourceConfig_BootFSPart(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					// Verify basic fields
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("path"),
						knownvalue.StringExact(imagePath),
					),
					// Verify bootfspart is populated (computed field)
					// When cloning, BCM auto-generates bootfspart UUID
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("bootfspart"),
						knownvalue.NotNull(),
					),
					// Also verify fspart is populated (related computed field)
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("fspart"),
						knownvalue.NotNull(),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Idempotency check - bootfspart should remain stable
			{
				Config: testAccCMPartSoftwareImageResourceConfig_BootFSPart(imageName, imagePath),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectEmptyPlan(),
					},
				},
				ConfigStateChecks: []statecheck.StateCheck{
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			// Import test - verify bootfspart persists through import
			{
				ResourceName:      "bcm_cmpart_softwareimage.test",
				ImportState:       true,
				ImportStateVerify: true,
				ImportStateVerifyIgnore: []string{
					"original_image", // Computed field for cloning - not returned by BCM after clone
					"force",          // Action parameter - not persisted in BCM state
				},
			},
		},
	})
}

func testAccCMPartSoftwareImageResourceConfig_BootFSPart(name, path string) string {
	return fmt.Sprintf(`
provider "bcm" {
  endpoint             = %[1]q
  username             = %[2]q
  password             = %[3]q
  insecure_skip_verify = true
}

# Lookup default-image to clone from (ensures bootfspart is populated)
data "bcm_cmpart_softwareimages" "default" {}

locals {
  default_image = [for img in data.bcm_cmpart_softwareimages.default.images : img if img.name == "default-image"][0]
}

# Clone from default-image to populate bootfspart and fspart
resource "bcm_cmpart_softwareimage" "test" {
  name           = %[4]q
  path           = %[5]q
  original_image = local.default_image.uuid
}
`,
		os.Getenv("BCM_ENDPOINT"),
		os.Getenv("BCM_USERNAME"),
		os.Getenv("BCM_PASSWORD"),
		name,
		path,
	)
}

// =============================================================================
// Import Test (Standalone)
// =============================================================================

// TestAccCMPartSoftwareImage_Import verifies that importing a software image by
// UUID produces state that matches a freshly applied configuration.
func TestAccCMPartSoftwareImage_Import(t *testing.T) {
	imageName := generateUniqueTestName("tftest-img-import")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	compareID := statecheck.CompareValue(compare.ValuesSame())

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					compareID.AddStateValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("id"),
					),
				},
			},
			{
				ResourceName:      "bcm_cmpart_softwareimage.test",
				ImportState:       true,
				ImportStateVerify: true,
				ImportStateVerifyIgnore: []string{
					"original_image",
					"force",
				},
			},
		},
	})
}

// =============================================================================
// Disappears Test
// =============================================================================

// softwareImageDisappearsCheck implements statecheck.StateCheck to simulate
// external deletion of a software image via the BCM API during a test step.
type softwareImageDisappearsCheck struct {
	resourceAddress string
}

func (c softwareImageDisappearsCheck) CheckState(ctx context.Context, req statecheck.CheckStateRequest, resp *statecheck.CheckStateResponse) {
	var imageUUID string
	for _, r := range req.State.Values.RootModule.Resources {
		if r.Address == c.resourceAddress {
			var ok bool
			imageUUID, ok = r.AttributeValues["uuid"].(string)
			if !ok || imageUUID == "" {
				resp.Error = fmt.Errorf("resource %s has no uuid attribute in state", c.resourceAddress)
				return
			}
			break
		}
	}

	if imageUUID == "" {
		resp.Error = fmt.Errorf("resource %s not found in state", c.resourceAddress)
		return
	}

	client := createTestBCMClient(&testing.T{})
	_, err := client.CallJSONRPC(ctx, "CMPart", "removeSoftwareImage", imageUUID, false, false, false)
	if err != nil {
		resp.Error = fmt.Errorf("failed to delete software image %s via BCM API: %w", imageUUID, err)
		return
	}

	time.Sleep(TestEventualConsistencyDelay)
}

// TestAccCMPartSoftwareImage_Disappears verifies that when a software image is
// deleted externally (outside Terraform), the next plan detects the disappearance.
func TestAccCMPartSoftwareImage_Disappears(t *testing.T) {
	imageName := generateUniqueTestName("tftest-img-disap")
	imagePath := fmt.Sprintf("/cm/images/%s", imageName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			testAccCMPartSoftwareImagePreCheck(t, imageName)
		},
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckCMPartSoftwareImageDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCMPartSoftwareImageResourceConfig_Basic(imageName, imagePath),
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						"bcm_cmpart_softwareimage.test",
						tfjsonpath.New("name"),
						knownvalue.StringExact(imageName),
					),
					softwareImageDisappearsCheck{resourceAddress: "bcm_cmpart_softwareimage.test"},
				},
				ExpectNonEmptyPlan: true,
			},
		},
	})
}
